### ISSUE TITLE
CT: Add a screen - ineligible as existing pass already exists

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#103]
This should link to the renewals/ replacements process as well as 'other ways to apply' in case the user believes they don't have a card issued

**Comment by suryanaga** [comment]
@irinapencheva Could you clarify what you mean by that last bit? Why would they go to 'other ways to apply' if they don't think they have a card? Just because they need to speak to someone in person? I think if that's the case it makes more sense to say "Contact us if you don't think you already have a pass."
