### ISSUE TITLE
add to prototype 'start page'

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#158]
@sanjaypoyzer 

Hi could you amend the page (https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/start-page) so that it has all the information in the service pattern section for start page?

I'm happy to write it up for you and then for you to edit if that makes things easier!

**Comment by suryanaga** [comment]
@EUzkuraityte Sure. Looks like more stuff was added whilst I was away and not updated on the start page.

Had a look and these are my thoughts

- the different types of permit the user can apply for (if applicable)
  - this should be a setting for the councils to change
- a postcode look up tool to check eligibility for available permits based on selected address (if deemed necessary by the council due to the complexity of available permits)
  - again, this should be a setting, but i do plan to build something for it soon
- permit eligibility requirements
  - this is in there
- where the permit they are applying for will allow them to park
  - this is in there
- at what time the permit they are applying for will allow them to park
  - this should be added
- how much the permit will cost
  - this is in there
- how long the permit is valid for
  - this should be added
- what information they need about the car for example number plate (registration number) of the vehicle
  - this will differ, but yeah should be added
- how long the process usually takes
  - this should be added
- what to do if they need assistance with the application
  - this needs to be added
- if the service differs from this pattern, include any other information the user needs to provide
  - will add a setting for councils to add additional content if they want

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer yup, sounds good, if we can also have sth re: links to renewals and replacements too it would be perfect! (sth like CT has)

**Comment by suryanaga** [comment]
Yep, that's issue #36

**Comment by suryanaga** [comment]
@EUzkuraityte Addressing a lot of this in PR #214 but some of the more local options I will do after we do the first round of user testing. If you can add separate issues for those options that would be great.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer sure, no probs! 

When you say 'options' is that renewals and replacements?

**Comment by suryanaga** [comment]
Basically anything that isn't going to be for all councils should be it's own issue and de-prioritised beneath first round of research
