### ISSUE TITLE
Do people need to know how much faster people receive their bus pass with Verify?

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#179]
On the 'verifying your identity' page we say "You'll receive your bus pass faster with Verify" - Would be good to put a number on this.

**Comment by irinapencheva** [comment]
#463 - findings from latest round of UR

**Comment by petegale** [comment]
Limited evidence from round 3 (2 users) suggests this need may have been met, but leaving open until we have better evidence of this.

**Comment by irinapencheva** [comment]
![screen shot 2017-06-14 at 14 48 43](https://user-images.githubusercontent.com/24913176/27135526-99d1082e-5110-11e7-80c9-1e7227fa66db.png)

Findings from latest round of user research suggests that this need is met for desktop users but there is a small improvement required for iPad users due to the issue below


![screen shot 2017-06-14 at 14 50 00](https://user-images.githubusercontent.com/24913176/27135587-cc032aca-5110-11e7-8de0-e0fd9ca5d70b.png)
