### ISSUE TITLE
Recently moved in & only resident's checks - Why were these removed?

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#206]

**Comment by suryanaga** [comment]
@euzkuraitye Do you know why these were removed?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer no clue.. could they have been deleted by mistake?

**Comment by suryanaga** [comment]
@kaydale @kateiw Any ideas?

**Comment by kateiw** [comment]
Not sure, @kaydale might know

**Comment by kaydale** [comment]
@sanjaypoyzer Just caught up with Kate. So the reason these scenarios were merged into the /not-eligible-permits-exceeded screen was because the outcome was the same but the message was different.
 
So the outcome would be the user needs to get in contact with the LA to cancel the existing permits. Under the assumption that old permits could not be cancelled until proof of tenancy is supplied to the LA which is why we handled it more like an exception route. If old permits could be cancelled without proof then that is a different story. 

I think we will probably need to have a conversation about this when your back from Newcastle for it to make sense haha.
