### ISSUE TITLE
Do users need email confirmation of their application and status updates while waiting?

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#24]
Thing to find out in research.

Comment from Herts:

"Could the user ask for an email confirmation? 

Not essential if we get the confirmation screen message right but maybe something we could add. However, we would need to ask for their email address at this point (as we don’t ask it anywhere else in the application and we wouldn’t get it from the identity provider)"

**Comment by kaydale** [comment]
From Pete:

Confirmations and reminders - User expressed a need for being kept up to date with progress of their application. Is there any opportunity to support progress / update notifications?

@sanjaypoyzer is this a separate issue as it speaks to "status of application" rather than confirmation of application being received.

**Comment by suryanaga** [comment]
@kaydale Let's leave it rolled up in here for now, and I'll edit the title to reflect that.

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 15 28 58](https://cloud.githubusercontent.com/assets/2970019/23556949/323fd824-0026-11e7-9abd-0502ffd2b29e.png)

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 15 28 47](https://cloud.githubusercontent.com/assets/2970019/23556992/5709d9de-0026-11e7-8d54-505df78c9ddf.png)
