### ISSUE TITLE
Users asked what size photo was required

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#348]

**Comment by irinapencheva** [comment]
@joanneSouthern - could you provide a little bit more detail on what exactly happened?

**Comment by lizziebruce** [comment]
@irinapencheva I suggest things that users will need to complete applications/transactions are listed out on first page of user journey. Similar issues #332 #356

**Comment by irinapencheva** [comment]
@lizziebruce - yes, sounds good! The only thing I'd be cautious is not listing too many things that users ultimately don't need to know (e.g. I'm not sure there needs to be a max. upload size specified prominently because for that demographic it could be more confusing; the size validation should happen in the back-end, and that should support high quality photographs as well)

@joanneSouthern - could you confirm exactly what users needed in terms of size confirmation? Did they want information on the data file size or how the framing of the actual photograph should be done (i.e. whether it's a passport photo) or something else?

**Comment by lizziebruce** [comment]
@irinapencheva @petegale perhaps worth keeping in mind as a raised issue and record whether there are any more instances of users asking about size in UR?

**Comment by irinapencheva** [comment]
@lizziebruce - agreed, let's do that!

**Comment by lizziebruce** [comment]
Ice-boxing for now

**Comment by irinapencheva** [comment]
@lizziebruce - I'll move as a ? to test in user research whether users have questions about the size of the photograph
