### ISSUE TITLE
users felt the process was too long winded, wouldn't recommend to a friend

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#353]

**Comment by suryanaga** [comment]
Without using a lower level of assurance, the only real option we have here is making it clearer to people before they start Verify that it will take a while

**Comment by petegale** [comment]
@sanjaypoyzer agreed - LOA1 is the only way to reduce the length of the Verify registration journey. However - perceptions such as these are usually indicative of an imbalance between effort and perceived value, so perhaps we can do something in terms of increasing perceived value?

Also - the design pattern for 'one thing per page' says that this should be the starting oint until user research suggests otherwise. Could this be a case of user research suggesting otherwise?

**Comment by suryanaga** [comment]
@petegale Yep, agreed that this could be linked to perceived value, although only if the user's quote came at the end of the process. Was that the case here @joanneSouthern?

Pete, which 'one thing per page' parts of the process do you think are contributing to the feeling that the process take a long time?

**Comment by petegale** [comment]
First thoughts on this, might be worth discussing in more detail

There are some elements of the journey that feel repetitive. I reckon they might be a good place to start. Could we consider "confirm your information is correct" as one thing? That could bring confirm address and confirm d.o.b. into one.

I wonder also wether those who are eligible need to be told they can proceed? Couldn't we just let them proceed and only include a page for those that aren't eligible?

**Comment by suryanaga** [comment]
Closing this as a duplicate of #190.
