### ISSUE TITLE
Users needed to find out if they're eligible but couldn't do so easily as they found the eligibility statement confusing

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#460]
Impact: Some were unsure if they could apply, and found the ‘Check pension age’ service confusing.

Evidence: Several users queried the statement referring to ‘female state pension age’ and those that used this link to check their eligibility were confused by the complexity of this service, and its focus on checking your pension.

**Comment by lizziebruce** [comment]
Suggested content redesign of the Start page resolves this issue. It's based on the inclusion of a widget to check DOB/bus pass eligibility. This widget would mean there's no need to send the user to Check pension age GOV.UK page or refer to female state pension age.  

> ## **Apply for an older person’s bus pass**
> 
> Older residents can get a free bus pass. When you can apply depends on when you were born. 
> 
> Enter your date of birth [  widget  ] 
> [Shows] Yes, you can apply now   [OR shows]    You can’t apply until 2020

**Comment by irinapencheva** [comment]
#94

**Comment by suryanaga** [comment]
For reference, here is the [state pension age table](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/310231/spa-timetable.pdf).

**Comment by lizziebruce** [comment]
Here's the bus pass age calculator: https://www.gov.uk/state-pension-age/y/bus_pass You just enter your DOB, click Next step and the next screen tells you the date you can get a bus pass from. There are some conditions/localised variations, which could be covered in the service page copy. As it already exists perhaps the calculator code can be embedded?

**Comment by lizziebruce** [comment]
@sanjaypoyzer and I explored ways to resculpt the DOB-dependent eligibility criteria this afternoon. Having the DOB checker embedded on the page isn't viable as user may click the Apply CTA instead of Return. So here are some new options. 

1. and 2. return the user to the Start page once they've checked DOB, 3. is has a mandatory second (and third) screen of the the application.

**Option 1 - loop DOB check as in-app Council site pages linked from How to apply steps on start page**

1.
![screen shot 2017-05-25 at 17 01 30](https://cloud.githubusercontent.com/assets/27814324/26461381/ef1a63ee-4174-11e7-8309-0e01a9edc438.png)

2.
![screen shot 2017-05-25 at 17 48 33](https://cloud.githubusercontent.com/assets/27814324/26461487/2dc4ccf6-4175-11e7-9ace-bb2cfe4b30ed.png)

3.
![screen shot 2017-05-25 at 17 48 25](https://cloud.githubusercontent.com/assets/27814324/26461504/38103bf0-4175-11e7-932a-f7b58b95f9ba.png)


**Option 2 - loop DOB check as in-app Council site pages from a dedicated section on start page**

1. 
![screen shot 2017-05-25 at 17 53 05](https://cloud.githubusercontent.com/assets/27814324/26461556/638d7018-4175-11e7-858b-200d3e06e45b.png)

2.
![screen shot 2017-05-25 at 17 48 33](https://cloud.githubusercontent.com/assets/27814324/26461487/2dc4ccf6-4175-11e7-9ace-bb2cfe4b30ed.png)

3.
![screen shot 2017-05-25 at 17 48 25](https://cloud.githubusercontent.com/assets/27814324/26461504/38103bf0-4175-11e7-932a-f7b58b95f9ba.png)

**Option 3 - DOB checker as the second page of the application, referenced as (not linked from) How to apply step 1** 

1.
![screen shot 2017-05-25 at 17 55 39](https://cloud.githubusercontent.com/assets/27814324/26461444/0faac716-4175-11e7-9db4-5c271d2579ff.png)

2.
![screen shot 2017-05-25 at 18 01 22](https://cloud.githubusercontent.com/assets/27814324/26461453/15a79496-4175-11e7-9816-ebab5a1bb7d5.png)

3.
![screen shot 2017-05-25 at 18 01 55](https://cloud.githubusercontent.com/assets/27814324/26461464/1c1f7b9a-4175-11e7-885b-1fe48757b997.png)

**Comment by irinapencheva** [comment]
@lizziebruce @sanjaypoyzer - great, thanks a lot for shaping those so quickly! 

I like all the options but would suggest we test with Option 2 unless there are some major issues.

**Comment by suryanaga** [comment]
I think option 2 is best as well, but I have a couple of ideas for us to discuss: 
 - Is "Enter your date of birth" the best text for the link? Would it be better with "Check if you're eligible"?
 - Does the order of the 3 sections above the button make the most sense?

**Comment by lizziebruce** [comment]
@sanjaypoyzer sure, let's discuss

**Comment by lizziebruce** [comment]
@irinapencheva not sure why you've moved this back to ready to do? has been fixed by PR #545 as far as I know.

<img width="565" alt="screen shot 2017-06-29 at 14 44 14" src="https://user-images.githubusercontent.com/27814324/27690608-b4f9314c-5cd9-11e7-90f4-68e7f489c384.png">

**Comment by irinapencheva** [comment]
@lizziebruce - don't remember why that has happened, my bad.

**Comment by lizziebruce** [comment]
Cool! No worries
