### ISSUE TITLE
Users wanted to choose the Verify route but thought they needed a Verify account in order to choose that route 

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#461]
Requires a rework on the Verifying your identity page

**Comment by lizziebruce** [comment]
@irinapencheva is this from before the recent changes to Verifying your identity page (now retitled Checking your identity)? Screenshot here:

<img width="555" alt="ct 2" src="https://cloud.githubusercontent.com/assets/27814324/25525812/8d9280d8-2c08-11e7-90f6-f57046483174.png">

**Comment by irinapencheva** [comment]
@lizziebruce - yes, that was just before the above change was implemented, so this is hopefully not as strong of an issue now. :)

You're probably on it, but this page should still be customised a bit for Con travel -changing from 'permits' to 'bus passes', adding the photo upload stuff, etc.
 
Do you think it's worth discussing whether it should be about 'checking your identity' or 'checking/proving your identity and eligibility'? I think there's something about users not understanding in first place why they have to prove their identity (we saw in UR  how they felt they're entitled to it without checks)

**Comment by lizziebruce** [comment]
@irinapencheva yes "permit" should've been changed to "bus pass" as per this screenshot below from just before we changed "identity" to "security". Not sure which issue I had uploaded that to! 
Re photo upload, that is to do with the bus pass application, asked for when user comes back to council site, so I would put that on the first page rather than in Verify radio button content. Am looking into content for that screen at mo (the first page). 
Re eligibility/ID checking, the line "We need to make sure you're eligible for a bus pass" should hopefully explain the ID checking, I think that had also changed from what was there previously, but I'll create some copy to convey "We need to check you're actually you" as that might really help with comprehension of Verify. 
![verify or scan options radio buttons](https://cloud.githubusercontent.com/assets/27814324/25526537/dcbaa69c-2c0b-11e7-8c80-d14114a8b73c.png)

**Comment by irinapencheva** [comment]
Great, sounds like a plan!

**Comment by lizziebruce** [comment]
@irinapencheva In fact this has already been addressed – shall we see if there is a positive improvement from this change to About the service? Also relevant for #413 

<img width="246" alt="screen shot 2017-04-28 at 12 44 52" src="https://cloud.githubusercontent.com/assets/27814324/25527559/241d4fee-2c11-11e7-8697-b457246b785f.png">

**Comment by lizziebruce** [comment]
NB I also recommended changing 'About this service' to 'About your application' to test if this makes people more likely to read it.

> About your application
> 1. Identify yourself using GOV.UK Verify, or by scanning documents.
> 2. Upload a digital photo.
> 2. Submit your application, we’ll send your bus pass by post.

**Comment by lizziebruce** [comment]
#413 is a related issue with screenshot of content fix

**Comment by lizziebruce** [comment]
As with #413 changes to the prototype (screenshots on 413) should help, specifically the copy about creating an account.

**Comment by petegale** [comment]
No evidence in round 3 that this issue remains
