### ISSUE TITLE
Eligible page: Oxfordshire

### ISSUE THREAD

**Issue by AbiBarkerOxfordshire** [alphagov/verify-local-patterns#550]
Sorry - I am not quite clear on whether we will be using this page or not so if not then this can be ignored. If it can't be ignored then could we change the wording to say you 'may' be eligible? We are unable to confirm eligibility due to our lack of API.

**Comment by EUzkuraityte** [comment]
@AbiBarkerOxfordshire would it be possible to get the API integration working at all? If not then I think it would be best not to show [the 'eligible' page](https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/eligible), simply because telling the user they may be eligible does not add any value to the user journey. What are your thoughts on this @lizziebruce @sanjaypoyzer ? What would you prefer?

**Comment by lizziebruce** [comment]
@EUzkuraityte I agree best not to show the eligible page in that scenario, as long as in this case the line about when the permit is valid for i.e. "Parking permits allow you to park in Argleton city centre 24 hours a day." appears on the subsequent page. Suggest it's placed just above "Permits can be for 6 or 12 months."

**Comment by suryanaga** [comment]
We're removing this page.
