### ISSUE TITLE
ConTravel: Content rewrite for service pattern page

### ISSUE THREAD

**Issue by kaydale** [alphagov/verify-local-patterns#56]
Northumberland feedback: "I dont think we can make comments about their income or ability to drive, its a mandatory requirement that councils must fulfill in England" 

In regards to "What is the user need?" content

**Comment by kaydale** [comment]
Warwickshire: 
We felt that the user need section was not reflective of the real situation.
There are a number of reasons why a citizen may want a concessionary travel pass and either this statement should be greatly expanded to include other use cases or it should be replaced with a simple statement that:
 
Under the provisions of the Transport Act 2000, as amended, in England outside London the statutory concession currently consists of guaranteed free off-peak travel for older and disabled people on all local buses anywhere in England from 0930 until 2300 on weekdays and all day at weekends and on Bank Holidays.
Ref:  HC Library briefing paper 1499

**Comment by anthonylord** [comment]
It's mandatory, the law, that councils must provide concessionary travel passes, but that's not a user need. It's not like taxes that everyone has to pay, not everyone that's eligible for a bus pass needs one. More info on user needs here for LAs: https://www.gov.uk/guidance/content-design/user-needs

I agree that what we shouldn't be saying this: 'As people get older, they are more likely to not be fit to drive. They also often retire from work, so their income goes down.' We should try to nail down a user need in this format:

As a… [who is the user?]
I need to… [what does the user want to do?]
So that… [why does the user want to do this?]

If we don't already have this, I'll need time to work on it.

**Comment by petegale** [comment]
I agree with Ant, and the other comments here about this paragraph.

I also like the idea of structuring this as a user need. How about something simple like:
As someone who is eligible to travel for free
I need to apply for a concessionary travel permit
So that I am able to prove my eligibility and travel for free
