### ISSUE TITLE
Users need the title of the pre-payment page to reflect the content

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#598]
![screen shot 2017-06-19 at 09 46 41](https://user-images.githubusercontent.com/20285115/27276799-392d33b8-54d4-11e7-8822-c487fbfac224.png)

Assigning this to Sanjay and Lizzie to advice on the service design and content copy.

**Comment by lizziebruce** [comment]
1. Suggest the page title is reworded:

> Your permit details

This would also work as a title for the summary page for free HMO permits. I don't think the "You're about the pay" line should change. It's preparing them for the next page (payment). The page title change should solve the issue. We could possibly add: 

> "Check your permit details and costs below."

2. This isn't the right place to mention the temporary permit. The focus of this page is what you're paying for and referring to a temp permit here would be distracting. We can solve this instead by adding copy to the [permit-start page](https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/permit-start)

so that for Verify users bullet one says: 

> As soon as possible – print a temporary permit at the end of your application

Thought re service design @sanjaypoyzer @EUzkuraityte Why do permits need to be sent out by post?? Is there a hallmark or hologram or anything like that on them? Can't we make a really good temporary permit... and then make that the full permit? I.e. if all the checks are done in-app, why can't we get the app to generate the actual permit at the end??

**Comment by lizziebruce** [comment]
hey @EUzkuraityte - full disclosure - just to let you know I edited my comment quite significantly since you thumbs upped it, just in case you want to retract the thumbs up! :-D

**Comment by EUzkuraityte** [comment]
@lizziebruce :D I'm going to keep the thumbs up and yes, usually there is a hologram printed on the parking permit

**Comment by lizziebruce** [comment]
@EUzkuraityte :-D Thanks and oh that's a shame. Also on 2. I've put the "as soon as poss" copy in 497 (referenced above).

**Comment by lizziebruce** [comment]
See also PR #607

**Comment by lizziebruce** [comment]
Update. I don't think this page should change title any more. It already has an alternative title for free permits: "Confirm your permit details."

I've added the line of copy "Check details and costs:" though.

After:

![screen shot 2017-06-23 at 15 58 32](https://user-images.githubusercontent.com/27814324/27487846-d71a1fe0-582c-11e7-8b53-8d90cf6ffe57.png)
