### ISSUE TITLE
BUG: need better wording for councils that offer unlimited number of permits

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#600]
See evidence from user research
![screen shot 2017-06-19 at 10 32 51](https://user-images.githubusercontent.com/20285115/27278974-ee4a72dc-54da-11e7-90ba-e54605b1af45.png)

**Comment by lizziebruce** [comment]
Solution: remove "up to" when unlimited number.

**Comment by lizziebruce** [comment]
Fixed with localisation for Cambridgeshire

![screen shot 2017-06-23 at 14 15 37](https://user-images.githubusercontent.com/27814324/27483759-96c29f34-581e-11e7-8bb3-f680c3eaf805.png)

<img width="818" alt="screen shot 2017-06-23 at 14 17 10" src="https://user-images.githubusercontent.com/27814324/27483798-b02b7dc4-581e-11e7-8057-cbe1a3c4aa85.png">
