### ISSUE TITLE
ConTravel: Could we move the order of confirming name and age first and address second? If the user changes their current address but then sees a DOB that is not theirs/makes them ineligible, they've wasted time to input new address. 

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#74]
This could be tested as part of UR to see what makes more sense

**Comment by kaydale** [comment]
@irinapencheva Kate & I discussed on Thursday that actually this checking DOB should be a background task that the user does not see. It is an extreme edge case that verify would return an incorrect address and thus I don't think we should include a step where the user can change their DOB. We will still include the page about communicating to the user that they are not eligible because of age - and we will add to this page the contact details for the LA.

**Comment by irinapencheva** [comment]
@kaydale - sounds good, are you updating the comments spreadsheet or shall I as that was a council comment?
