### ISSUE TITLE
Can the age check at the start be internalised, rather than on a separate webpage?

### ISSUE THREAD

**Issue by ghost** [alphagov/verify-local-patterns#94]
The GOV.UK service to check pension age is a bit old in the tooth (e.g. select boxes) - perhaps this should be improved? Alternatively, given the relative simplicity of the date logic, should this 'check' be part of the new service, rather than solely something independent?

**Comment by samuelculley** [comment]
The page stating that a user is not eligible for a bus pass because of age might make it clearer that the person is not eligible yet. For London again, the first availability will be for the 60+ Oyster card, so this message should similar inform the user of the specific date they become available for the 60+ Oyster card, and provide a call-to-action for the user to go the right page on the TfL site.

**Comment by suryanaga** [comment]
Possibly.

What is the date logic here? I could potentially build a thing which does this.

**Comment by suryanaga** [comment]
@irinapencheva Suggest we move this down as we've seen no need for it in research.

**Comment by irinapencheva** [comment]
@sanjaypoyzer - OK, happy to move for now
@petegale - in this or a later round of UR, could we look at this?

**Comment by irinapencheva** [comment]
Closing this issue as it's referenced in #460
